### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by tabmoo3000** [onyphe/client#1]
Hi, I am getting the following error when i try to follow the install instructions. 

root@kali:~/onyphe# sudo perl -MMetabrik::Core::Context -e \
>      'Metabrik::Core::Context->new_brik_run("brik::tool", "install", \
>      "api::onyphe")'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  couchdb dissy erlang17-asn1 erlang17-base erlang17-crypto erlang17-eunit erlang17-inets erlang17-mnesia erlang17-os-mon erlang17-public-key
  erlang17-runtime-tools erlang17-snmp erlang17-ssl erlang17-syntax-tools erlang17-tools erlang17-webtool erlang17-xmerl geoip-database-extra
  gir1.2-harfbuzz-0.0 gir1.2-mutter-1 gir1.2-mutter-2 gir1.2-networkmanager-1.0 gir1.2-nmgtk-1.0 glusterfs-common gnome-themes-standard guile-2.0-libs
  gvfs-bin keepnote libacl1-dev libann0 libappindicator1 libargon2-0 libarmadillo7 libarmadillo8 libattr1-dev libavahi-gobject0 libavfilter6 libavformat57
  libavresample3 libbabeltrace-ctf1 libbind9-141 libbind9-160 libboost-atomic1.62.0 libboost-chrono1.62.0 libboost-date-time1.62.0 libboost-filesystem1.62.0
  libboost-iostreams1.62.0 libboost-program-options1.62.0 libboost-random1.62.0 libboost-serialization1.62.0 libboost-test1.62.0 libboost-timer1.62.0
  libcamel-1.2-60 libcamel-1.2-61 libcaribou-gtk-module libcaribou-gtk3-module libcdio-cdda1 libcdio-paranoia1 libcdio13 libcdio17 libcephfs1 libcgal12
  libchamplain-0.12-0 libcharls1 libcue1 libdbusmenu-gtk4 libdigest-md5-file-perl libdns-export1102 libdns-export169 libdns1102 libdns169 libdns190
  libedataserver-1.2-22 libedataserverui-1.2-1 libenca0 libevent-2.0-5 libfile-copy-recursive-perl libfolks-telepathy25 libfreerdp-cache1.1
  libfreerdp-client1.1 libfreerdp-codec1.1 libfreerdp-common1.1.0 libfreerdp-core1.1 libfreerdp-crypto1.1 libfreerdp-gdi1.1 libfreerdp-locale1.1
  libfreerdp-primitives1.1 libfreerdp-utils1.1 libgail-3-0 libgcab-1.0-0 libgcr-3-common libgdbm5 libgdcm2.8 libgeos-3.5.1 libgeos-3.6.2 libgeos-3.7.0
  libgfortran4 libgl2ps1.4 libglib2.0-dev libglib2.0-dev-bin libgnome-desktop-3-12 libgom-1.0-common libgraphite2-dev libgtk2-perl libgweather-3-6
  libharfbuzz-dev libharfbuzz-gobject0 libhdf5-openmpi-103 libhttp-parser2.1 libhttp-parser2.7.1 libhttp-server-simple-perl libhunspell-1.6-0 libical2
  libicu-le-hb-dev libilmbase12 libindicator7 libipt1 libirs160 libisc-export166 libisc-export169 libisc166 libisc169 libisc189 libisccc140 libisccc160
  libisccfg144 libisccfg160 libisl15 libjs-excanvas libjs-jquery-form libjs-openlayers liblept5 libllvm5.0 liblouis14 liblwgeom-2.4-0 liblwres141
  liblwres160 libmagickcore-6.q16-3 libmagickcore-6.q16-3-extra libmagickcore-6.q16-5 libmagickcore-6.q16-5-extra libmagickwand-6.q16-3
  libmagickwand-6.q16-5 libmozjs185-1.0 libmpfr4 libmutter-1-0 libmutter-2-0 libnetcdf-c++4 libnfs8 libnm-glib4 libnm-gtk0 libnm-util2 libntfs-3g872
  libobjc-6-dev libobjc-7-dev libomp5 libopencv-calib3d3.2 libopencv-contrib3.2 libopencv-core3.2 libopencv-features2d3.2 libopencv-flann3.2
  libopencv-highgui3.2 libopencv-imgcodecs3.2 libopencv-imgproc3.2 libopencv-ml3.2 libopencv-objdetect3.2 libopencv-photo3.2 libopencv-shape3.2
  libopencv-stitching3.2 libopencv-superres3.2 libopencv-video3.2 libopencv-videoio3.2 libopencv-videostab3.2 libopencv-viz3.2 libopenexr22 libopenmpi2
  libpango-perl libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libperl5.26 libpoppler68 libpoppler72 libpoppler74 libpostproc54 libproj12
  libprotobuf-lite10 libprotobuf10 libpython3.6 libpython3.6-dev libqcustomplot1.3 libqgis-core2.14.20 libqgis-core2.14.21 libqgis-core2.18.17
  libqgis-core2.18.23 libqgis-gui2.18.17 libqgis-gui2.18.23 libqgis-networkanalysis2.14.20 libqgis-networkanalysis2.14.21 libqgis-networkanalysis2.18.17
  libqgis-networkanalysis2.18.23 libqgispython2.14.20 libqgispython2.14.21 libqgispython2.18.17 libqgispython2.18.23 libqwt5-qt4 libradare2-2.0
  libradare2-2.1 libradare2-2.4 libradare2-2.9 libruby2.3 libsane-extras libsane-extras-common libsctp1 libsocket++1 libsodium18 libsrtp0 libstdc++-6-dev
  libswscale4 libsynctex1 libtbb2 libtcl8.5 libtelepathy-glib0 libtesseract-data libtesseract3 libtesseract4 libtk8.5 libtxc-dxtn-s2tc libunbound2 libvpx4
  libvtk6.3 libwayland-egl1-mesa libwhisker2-perl libwinpr-crt0.1 libwinpr-crypto0.1 libwinpr-dsparse0.1 libwinpr-environment0.1 libwinpr-file0.1
  libwinpr-handle0.1 libwinpr-heap0.1 libwinpr-input0.1 libwinpr-interlocked0.1 libwinpr-library0.1 libwinpr-path0.1 libwinpr-pool0.1 libwinpr-registry0.1
  libwinpr-rpc0.1 libwinpr-sspi0.1 libwinpr-synch0.1 libwinpr-sysinfo0.1 libwinpr-thread0.1 libwinpr-utils0.1 libwireshark10 libwiretap7 libwscodecs1
  libwsutil8 libwww-mechanize-perl libx264-148 libx265-130 libx265-160 libxerces-c3.1 libxfont1 linux-compiler-gcc-6-x86 linux-headers-4.13.0-kali1-amd64
  linux-headers-4.13.0-kali1-common linux-headers-4.14.0-kali1-amd64 linux-headers-4.14.0-kali1-common linux-headers-4.14.0-kali3-amd64
  linux-headers-4.14.0-kali3-common linux-image-4.13.0-kali1-amd64 linux-image-4.14.0-kali1-amd64 linux-image-4.14.0-kali3-amd64 linux-kbuild-4.13
  linux-kbuild-4.14 open-coarrays-bin openjdk-10-jdk openjdk-10-jdk-headless openjdk-10-jre openjdk-8-jdk openjdk-8-jdk-headless php7.0-mysql php7.2-mysql
  python-anyjson python-backports.ssl-match-hostname python-beautifulsoup python-brotli python-bson python-bson-ext python-capstone python-couchdbkit
  python-cssutils python-functools32 python-gridfs python-http-parser python-httpretty python-imaging python-jwt python-pam python-ply python-pycryptodome
  python-pymongo python-pymongo-ext python-pysmi python-pysnmp4 python-pysnmp4-apps python-pysnmp4-mibs python-restkit python-rsvg python-socketpool
  python3-argcomplete python3-argh python3-construct python3-cssutils python3-editorconfig python3-feedparser python3-flask python3-html2text
  python3-itsdangerous python3-jsbeautifier python3-jwt python3-pathtools python3-prettytable python3-pyinotify python3-simplejson python3-watchdog
  python3-werkzeug python3.6-dev ruby-terminal-table ruby-unicode-display-width ruby2.3 ruby2.3-dev smitools tk8.5 vino x11proto-dri2-dev x11proto-gl-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1377 not upgraded.
Usage: cpanm [options] Module [...]

Try `cpanm --help` or `man cpanm` for more options.
[-] core::context: call: Can't locate object method "new_from_brik_no_checks" via package "Metabrik::SCALAR(0x559244893c48)" at /usr/local/share/perl/5.28.1/Metabrik/Brik/Tool.pm line 522.

**Comment by onyphe** [comment]
Hello,

sorry for being late in replying, we don't receive notifications on issues.
The doc is buggy, we will fix that. Could you try with the following command instead (remove \ characters):

sudo perl -MMetabrik::Core::Context -e 'Metabrik::Core::Context->new_brik_run("brik::tool", "install", "api::onyphe")'

Best regards,
